import 'package:flutter/material.dart';

import 'project_widget.dart';

List<Widget> projectWidgetList = [
  ProjectWidget(
    projectNumber: 1,
    gradientOne: Colors.white,
    gradientTwo: Color(0xFF40c4ff),
    projectTextColor: Colors.black,
    projectTitle: 'State management',
    projectDescription:
        'Demonstrating state management in Flutter. Highlighting Flutter architecture choices using the Provider package to manage app state.',
    projectImage: 'todoey',
    projectLink: 'github.com/WD-J/todoey',
  ),
  ProjectWidget(
    projectNumber: 1,
    gradientOne: Color(0xFF0a0e21),
    gradientTwo: Color(0xFFeb1555),
    projectTextColor: Colors.white,
    projectTitle: 'Building intermediate UI',
    projectDescription: 'Customising Flutter Widgets to achieve beautiful user interface designs.',
    projectImage: 'bmi',
    projectLink: 'github.com/WD-J/bmi-calculator',
  ),
  ProjectWidget(
    projectNumber: 1,
    gradientOne: Color(0xFF2ab574),
    gradientTwo: Color(0xFF2f3338),
    projectTextColor: Colors.white,
    projectTitle: 'Text',
    projectDescription: 'A rounded out, fully functional chatting application, focusing on group chat functionality.',
    projectImage: 'text',
    projectLink: 'github.com/WD-J/Text',
  ),
  ProjectWidget(
    projectNumber: 1,
    gradientOne: Color(0xFF2f3338),
    gradientTwo: Colors.white,
    projectTextColor: Colors.white,
    projectTitle: 'WikiLeaks News',
    projectDescription: 'An application demonstrating web scraping, including a forum esque, Firebase back-end.',
    projectImage: 'wikileaks_news',
    projectLink: 'github.com/WD-J/Wikileaks-News',
  ),
  ProjectWidget(
    projectNumber: 1,
    gradientOne: Color(0xFF212121),
    gradientTwo: Color(0xFFf44336),
    projectTextColor: Colors.white,
    projectTitle: 'Modularised & Organised Flutter code',
    projectDescription: 'Displaying core programming concepts and using Stateful Flutter widgets.',
    projectImage: 'quizzler',
    projectLink: 'github.com/WD-J/quizzler',
  ),
  ProjectWidget(
    projectNumber: 1,
    gradientOne: Color(0xFFf44336),
    gradientTwo: Colors.white,
    projectTextColor: Colors.white,
    projectTitle: 'Clean state demonstration',
    projectDescription: 'Displaying core programming concepts and using Stateful Flutter widgets.',
    projectImage: 'dicee',
    projectLink: 'github.com/WD-J/dicee',
  ),
  ProjectWidget(
    projectNumber: 1,
    gradientOne: Colors.white,
    gradientTwo: Color(0xFF40c4ff),
    projectTextColor: Colors.black,
    projectTitle: 'Firebase Cloud & Firestore',
    projectDescription:
        'Incorporating Firebase into Flutter apps. In this case, highlighting Firebase Cloud Firestore as well as the Firebase authentication - cloud based NoSQL database and secure authentication methods.',
    projectImage: 'flashchat',
    projectLink: 'github.com/WD-J/flash-chat',
  ),
  ProjectWidget(
    projectNumber: 3,
    gradientOne: Colors.white,
    gradientTwo: Colors.transparent,
    projectTextColor: Colors.white,
    projectTitle: 'Libraries and basic audio management',
    projectDescription:
        'Demonstrating Dart programming concepts such as lists, loops, functions, etc, as well as using libraries, and managing audio.',
    projectImage: 'xylophone',
    projectLink: 'github.com/WD-J/xylophone',
  ),
  ProjectWidget(
    projectNumber: 1,
    gradientOne: Color(0xFF40c4ff),
    gradientTwo: Colors.white,
    projectTextColor: Colors.black,
    projectTitle: 'Basic parameter based API handling',
    projectDescription: 'Demonstrating conditional REST-API handling, and natively using Cupertino and Material Widgets in parallel.',
    projectImage: 'cointicker',
    projectLink: 'github.com/WD-J/bitcoin-ticker',
  ),
  ProjectWidget(
    projectNumber: 1,
    gradientOne: Color(0xFF2c2b27),
    gradientTwo: Colors.white,
    projectTextColor: Colors.white,
    projectTitle: 'Asynchronous API handling',
    projectDescription: 'Demonstrating asynchronous programming in Dart, using device location and networking.',
    projectImage: 'clima',
    projectLink: 'github.com/WD-J/clima',
  ),
];
